---
- name: Install Tomcat Server
  hosts: all
  become: yes
  
  tasks:
  - name: Update the system packages
    package:
      name: '*'
      state: latest
      
  - name: Install Java
    package:
      name: openjdk-11-jdk
      state: present
      
  - name: Download Tomcat
    get_url:
      url: http://apachemirror.wuchna.com/tomcat/tomcat-9/v9.0.40/bin/apache-tomcat-9.0.40.tar.gz
      dest: /tmp/
      
  - name: Extract Tomcat
    unarchive:
      src: /tmp/apache-tomcat-9.0.40.tar.gz
      dest: /opt/
      remote_src: yes
      
  - name: Set Tomcat Permissions
    file:
      path: /opt/apache-tomcat-9.0.40
      owner: tomcat
      group: tomcat
      mode: '0755'
      
  - name: Create Tomcat Service
    copy:
      src: tomcat.service
      dest: /etc/systemd/system/
      owner: root
      group: root
      mode: '0644'
      
  - name: Reload Systemd
    command: systemctl daemon-reload
    
  - name: Enable Tomcat Service
    command: systemctl enable tomcat
    
  - name: Start Tomcat Service
    command: systemctl start tomcat
	
  - name: Connect to Tomcat server on port 9090 and check status 200 - Try 5 times
    tags: test
    uri:
      url: http://localhost:9090
    register: result
    until: "result.status == 200"
    retries: 5
    delay: 10
